apiVersion: apps/v1
kind: Deployment

metadata:
  name: fortune-deployment
  namespace: fortune

spec:
  replicas: 2
  
  selector:
    matchLabels:
      app.kubernetes.io/name: fortune-pod
  
  template:
    metadata:
      name: fortune-pod
      labels:
        app.kubernetes.io/name: fortune-pod
        app.kubernetes.io/version: "v1"
    
    spec:
      containers:
      - name: fortune
        image: staelen/fortune
        imagePullPolicy: Always
        env:
        - name: APP_PORT
          value: "3000"
        ports: 
        - name: fortune-port
          containerPort: 3000
