apiVersion: v1
kind: Service
metadata:
  name: bgg-app-service
  namespace: bgg
  labels:
    name: bgg-app-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: bgg-app-pod
  ports:
  - name: bdd-app-service-port
    port: 80
    targetPort: bgg-app-port
