apiVersion: v1
kind: Service
metadata:
  name: {{ include "exchange-rate-chart.fullname" . }}
  labels:
{{ include "exchange-rate-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app-port
      protocol: TCP
      name: service-port
  selector:
    app.kubernetes.io/name: {{ include "exchange-rate-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
