apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: bgg-db-pvc
  namespace: bgg
  annotations:
    volume.beta.kubernetes.io/storage-provision: dobs.csi.digitalocean.com

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage